services:
  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka_broker:
    container_name: kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: kafka-topics --bootstrap-server kafka_broker:9092 --list
      interval: 20s
      timeout: 10s
      retries: 5
  init-kafka:
    container_name: init_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      kafka_broker:
        condition: service_healthy
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka_broker:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka_broker:9092 --create --topic testjs --replication-factor 5 --partitions 8

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka_broker:9092 --list
      "
  producer:
    container_name: bid_producer
    build: ./Producer
    depends_on:
      init-kafka:
        condition: service_completed_successfully
  bid_analytics:
    container_name: bid_analytics
    build: ./Consumer
    environment:
      - KAFKA_ID=bid_analytics
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      
  bid_capture:
    container_name: bid_capture
    build: ./Consumer
    environment:
      - KAFKA_ID=bid_capture
    depends_on:
      init-kafka:
        condition: service_completed_successfully
  bid_tracking:
    container_name: bid_tracking
    build: ./Consumer
    environment:
      - KAFKA_ID=bid_tracking
    depends_on:
      init-kafka:
        condition: service_completed_successfully