services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka_broker:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: kafka-topics --bootstrap-server kafka_broker:9092 --list
      interval: 20s
      timeout: 10s
      retries: 5
  bid_capture_sub:
    build: ./Capture
    depends_on:
      kafka_broker:
        condition: service_healthy
  bid_tracking_sub:
    build: ./Tracking
    depends_on:
      kafka_broker:
        condition: service_healthy
  bid_analytics_sub:
    build: ./Analytics
    depends_on:
      kafka_broker:
        condition: service_healthy
  bid_producer_pub:
    build: ./Producer
    depends_on:
      kafka_broker:
        condition: service_healthy